#!/bin/bash
./run-ggplot2-days.sh OneInitialInfected/WithoutExtScreening/WithCountermeasures/WithoutVaccinatedInfectious A1 WithoutScreening Screening25 Screening50 Screening100

./run-ggplot2-days.sh OneInitialInfected/WithoutExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D1 WithoutScreening Screening25 Screening50 Screening100

./run-ggplot2-days.sh OneInitialInfected/WithoutExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D2 WithoutScreening Screening25 Screening50 Screening100

python3 run-ggplot2-positive-comparison.py OneInitialInfected/WithoutExtScreening/WithCountermeasures/WithoutVaccinatedInfectious