#!/bin/bash
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious A1 Monday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious A1 Tuesday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious A1 Wednesday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious A1 Thursday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious A1 Friday WithoutScreening Screening25 Screening50 Screening100

./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D1 Monday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D1 Tuesday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D1 Wednesday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D1 Thursday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D1 Friday WithoutScreening Screening25 Screening50 Screening100

./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D2 MondayWednesday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D2 TuesdayThursday WithoutScreening Screening25 Screening50 Screening100
./run-ggplot2.sh OneInitialInfected/WithExtScreening/WithCountermeasures/WithoutVaccinatedInfectious D2 WednesdayFriday WithoutScreening Screening25 Screening50 Screening100